// Offline FAQ used when the AI service is off, busy or rate limited. Facts match the site copy.
const K=[
{k:['what','does','vaani','kya','karta','करता','क्या','काय','करतो','about'],a:{en:'Vaani turns a daily-sales CSV (cash, UPI, new credit) into checked totals and a short brief you can read, and hear if your phone has a matching voice. You keep your billing software.',hi:'Vaani दैनिक बिक्री की CSV (कैश, UPI, नया उधार) से जांचे हुए आंकड़े और छोटा सारांश बनाता है। फोन में सही आवाज़ हो तो सुन भी सकते हैं। आपका बिलिंग सॉफ्टवेयर वैसा ही रहता है।',mr:'Vaani दैनिक विक्रीच्या CSV (रोख, UPI, नवीन उधार) वरून तपासलेले आकडे आणि छोटा सारांश देतो. फोनमध्ये योग्य आवाज असेल तर ऐकताही येतो. तुमचे बिलिंग सॉफ्टवेअर तसेच राहते.'}},
{k:['safe','data','privacy','upload','leave','सुरक्षित','डेटा','सुरक्षित'],a:{en:'The CSV is read inside your browser tab and is not uploaded. Refresh to clear it. Account and demo-request data is separate and uses Firebase. Please do not include customer or patient details.',hi:'CSV आपके ब्राउज़र टैब में ही पढ़ी जाती है, अपलोड नहीं होती। रिफ्रेश करने पर साफ हो जाती है। अकाउंट और डेमो रिक्वेस्ट का डेटा अलग है और Firebase पर रहता है। ग्राहक या मरीज की जानकारी न डालें।',mr:'CSV तुमच्या ब्राउझर टॅबमध्येच वाचली जाते, अपलोड होत नाही. रिफ्रेश केल्यावर पुसली जाते. खाते आणि डेमो विनंतीचा डेटा वेगळा असून Firebase वर राहतो. ग्राहक किंवा रुग्णांची माहिती टाकू नका.'}},
{k:['csv','format','file','column','excel','xlsx','कौन','सी','कोणती','हवी'],a:{en:'Use one row per day with date (YYYY-MM-DD), cash, upi and credit columns. Amounts are rupees, numbers only. Credit means new credit sales that day, not total outstanding. XLSX is not supported yet. You can download the sample from the demo section.',hi:'हर दिन की एक पंक्ति: date (YYYY-MM-DD), cash, upi, credit कॉलम। रकम रुपये में, सिर्फ संख्या। Credit यानी उस दिन का नया उधार, कुल बकाया नहीं। XLSX अभी नहीं चलती। डेमो सेक्शन से सैंपल डाउनलोड करें।',mr:'दररोज एक ओळ: date (YYYY-MM-DD), cash, upi, credit कॉलम. रक्कम रुपयांत, फक्त आकडे. Credit म्हणजे त्या दिवसाची नवीन उधारी, एकूण बाकी नव्हे. XLSX अजून चालत नाही. डेमो विभागातून सॅम्पल डाउनलोड करा.'}},
{k:['price','cost','free','pay','charge','fee','कीमत','कितना','किंमत','किती','पैसे'],a:{en:'The local demo is free, with no card or checkout. Any future paid pilot would be agreed separately with Sagar. No price is fixed yet.',hi:'लोकल डेमो मुफ्त है, कार्ड या पेमेंट नहीं। भविष्य का कोई पेड पायलट Sagar से अलग से तय होगा। अभी कोई कीमत तय नहीं है।',mr:'लोकल डेमो मोफत आहे, कार्ड किंवा पेमेंट नाही. पुढचा कोणताही पेड पायलट Sagar शी वेगळा ठरेल. अजून किंमत ठरलेली नाही.'}},
{k:['whatsapp','voice','audio','hear','sun','सुन','ऐक','आवाज'],a:{en:'Read aloud uses a matching voice installed on your device, so Hindi or Marathi audio is not guaranteed. The text brief always works. Automated WhatsApp voice notes are not connected yet.',hi:'सुनाने के लिए आपके फोन में मेल खाती आवाज़ चाहिए, इसलिए हिंदी या मराठी ऑडियो की गारंटी नहीं। लिखित सारांश हमेशा चलता है। WhatsApp पर अपने आप वॉइस नोट अभी जुड़ा नहीं है।',mr:'ऐकवण्यासाठी फोनमध्ये योग्य आवाज हवा, त्यामुळे हिंदी किंवा मराठी ऑडिओची खात्री नाही. लिखित सारांश नेहमी चालतो. WhatsApp वर आपोआप व्हॉइस नोट अजून जोडलेली नाही.'}},
{k:['udhaar','expiry','gst','tally','billing','sync','उधार','एक्सपायरी'],a:{en:'Not in this version: live billing sync, overdue udhaar, near-expiry alerts, GST, payments. Those need different data and separate checking. This pilot covers daily totals only.',hi:'इस वर्शन में नहीं: लाइव बिलिंग सिंक, बकाया उधार, एक्सपायरी अलर्ट, GST, पेमेंट। इनके लिए अलग डेटा चाहिए। अभी सिर्फ दैनिक कुल आंकड़े हैं।',mr:'या आवृत्तीत नाही: लाइव्ह बिलिंग सिंक, थकीत उधारी, एक्सपायरी अलर्ट, GST, पेमेंट. त्यासाठी वेगळा डेटा लागतो. सध्या फक्त दैनिक एकूण आकडे आहेत.'}},
{k:['contact','demo','email','sagar','talk','संपर्क','मेल'],a:{en:'Email Sagar at sagaranwekar99@gmail.com, or use the optional account and demo request section on this page.',hi:'Sagar को sagaranwekar99@gmail.com पर ईमेल करें, या इसी पेज पर अकाउंट और डेमो रिक्वेस्ट सेक्शन इस्तेमाल करें।',mr:'Sagar ला sagaranwekar99@gmail.com वर ईमेल करा, किंवा याच पेजवरील खाते आणि डेमो विनंती विभाग वापरा.'}}];
const FALL={en:'I am not sure about that. I can help with what Vaani does, the CSV format, privacy, price and what is not ready yet. For anything else, email Sagar at sagaranwekar99@gmail.com.',hi:'इस बारे में मुझे पक्का पता नहीं। मैं Vaani क्या करता है, CSV फॉर्मेट, प्राइवेसी, कीमत और क्या तैयार नहीं है, इसमें मदद कर सकता हूं। बाकी के लिए Sagar को sagaranwekar99@gmail.com पर ईमेल करें।',mr:'याबद्दल मला खात्री नाही. Vaani काय करतो, CSV फॉर्मेट, प्रायव्हसी, किंमत आणि काय तयार नाही यात मी मदत करू शकतो. इतरांसाठी Sagar ला sagaranwekar99@gmail.com वर ईमेल करा.'};
export function offlineAnswer(text:string,lang='en'){const s=text.toLowerCase();let best=null,sc=0;for(const e of K){const n=e.k.filter(w=>s.includes(w)).length;if(n>sc){sc=n;best=e}}
if(best&&sc>0)return best.a[lang]||best.a.en;return FALL[lang]||FALL.en}
